# This file is used to configure the developer tasks
# defined in the vagrant/Makefile
config_folder = ../config-example

# This is the database id for the default REDCap project
redcap_project_id = 12

# This is the list of forms exported from the REDCap project
redcap_project_forms = enrollment, chemistry, cbc

# This the name of the enrollment form
# which needs to be imported before any data can be sent to REDCap
redcap_project_enrollment_form = enrollment
